name: License Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-licenses:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.4'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.10'
      - name: Prerequisites
        run: |
          sudo apt-get install jq
          pip install yq flict
          gem install license_finder
      - name: Lint licenses
        run: make lint.licenses
